#!/usr/bin/env python

import os
from resgds import *
import bragg
import gdspy # gds library
import numpy as np
from subprocess import call # Use to call kaloput_viewer bash script
import psutil # Use to check if klayout is running already   

# Layout filename
layout_file = 'bragg.gds'

# Parameters
sub_x = 10000
sub_y = 10000

wc = 8.11 # Conductor width of cavity
gc = 17.85 # Gap b/w conductor and substrate
lc = 8108.45 # Length of cavity

wlow = 30.44  # Width of low impedance section
glow = .5*(wc + 2*gc - wlow) # Gap of low impedance section
llow = 4051.32 # Length of low impedance section

whigh = 2 # 
ghigh = .5*(wlow + 2*glow - whigh)
lhigh = 4051.32

rext = 0 # extrude radius
rlow = 50 # Radius of low impedance section
rhigh = 50 # Radius of high impedance section

lext1 = 400 # Lengths of straigh extrude sections
lext2 = 1200

lext3 = llow - lext1 - lext2 - 500*np.pi - 150*np.pi

# Setup gds cell and gds object
poly_cell = gdspy.Cell('POLYGONS')
rs = Shapes(poly_cell)

# Substrate [layer 0]
sub = BuildRect(poly_cell, sub_x, sub_y, layer=0)
sub.make(0,0)

coords = lambda x,dx=0: x+dx

# Centre Cavity [layer 1]
x0, y0 = [coords(sub_x/2, -lc/2), coords(sub_y/2, -2*(wc/2) - gc/2)]

cavity = Trench(wc, gc, poly_cell, layer=1)
cavity.straight_trench(lc, x0, y0, orient='H')

# Low Z extrudance from Cavity (LHS) [layer 1]
Zlow = Trench(wlow, glow, poly_cell, layer=1)
Zlow.halfarc_trench(rlow, x0, y0-rlow, orient='W', npoints=40)
Zlow.halfarc_trench(rlow, sub_x - x0, y0 + rlow + wlow + 2*glow, orient='E', npoints=40)

x1,y1 = [coords(x0), coords(y0,-2*rlow-2*glow-wlow)]
Zlow.straight_trench(lext1,x1,y1,orient='H')
Zlow.straight_trench(lext1,sub_x-x1-lext1,y1+4*rlow + 2*wlow + 4*glow,orient='H')

x2,y2 = [coords(x0,lext1), coords(y0,-2*rlow-wlow-2*glow)]
Zlow.quarterarc_trench(rext,x2,y2,orient='NE',npoints=20)
Zlow.quarterarc_trench(rext,sub_x-x2,sub_y/2,orient='SW',npoints=20)

x3,y3 = [coords(x2),coords(y2,-lext2)]
Zlow.straight_trench(lext2, x3, y3, orient='V')

x4,y4 = [coords(x3, wlow + 2*glow + rlow),coords(y3)]
Zlow.halfarc_trench(rlow,x4,y4,orient='S',npoints=40)

x5,y5 = [coords(x4,rlow),coords(y4)]
Zlow.straight_trench(lext3, x5, y5, orient='V')

# Bragg Mirror Sections [layer 1]
no_periods = 4

xb_strt,yb_strt = [coords(x5),coords(y5,lext3)]

highZ = bragg.Bragg(whigh, ghigh, lhigh, poly_cell, radius=rhigh, layer=1)
lowZ = bragg.Bragg(wlow, glow, llow, poly_cell, radius=rlow, layer=1)

arr_l = np.repeat(np.arange(0,no_periods),2*np.ones(no_periods,dtype=int))
arr_h = np.append(arr_l[1:],[no_periods], axis=0)

make_lowZ = lambda i: lowZ.mirror(xb_strt + arr_h[i]*highZ.mirror_width()
        + arr_l[i]*lowZ.mirror_width(), yb_strt) 
make_highZ = lambda i: highZ.mirror(xb_strt + arr_h[i]*highZ.mirror_width()
        + arr_l[i]*lowZ.mirror_width(), yb_strt) 

[make_lowZ(x) for x in range(len(arr_l)) if x % 2 == 1]
[make_highZ(x) for x in range(len(arr_l)) if x % 2 == 0]



# Check if klayout is already running. If not, write gds and open klayout. 
# If it is, just update the gds file
if("klayout" in (p.name() for p in psutil.process_iter())):
    #Write the pattern as a gds file
    gdspy.write_gds(layout_file, unit=1.0e-6, precision=1.0e-9)
else:
    gdspy.write_gds(layout_file, unit=1.0e-6, precision=1.0e-9)
    kl = call('./klayout_viewer %s' %layout_file,shell=True)

